# Generated by Django 6.1.1 on 2026-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatuser',
            name='unique_chat_user_source_external_id',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='bot_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chatuser',
            constraint=models.UniqueConstraint(fields=('source', 'bot_id', 'external_id'), name='unique_chat_user_source_bot_external'),
        ),
    ]
