# Generated by Django 6.1.1 on 2026-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='social_media',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
