# Generated by Django 6.1.1 on 2026-10-07 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('word_count', models.PositiveIntegerField()),
                ('headings', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('language', models.CharField(default='fa', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('planning', 'Planning'), ('researching', 'Researching'), ('writing', 'Writing'), ('reviewing', 'Reviewing'), ('revising', 'Revising'), ('final_review', 'Final review'), ('editing', 'Editing'), ('quality_check', 'Quality check'), ('rendering', 'Rendering'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancel_requested', 'Cancellation requested'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_stage', models.CharField(default='Queued', max_length=255)),
                ('current_section', models.PositiveSmallIntegerField(default=0)),
                ('total_sections', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request_payload', models.JSONField(default=dict)),
                ('plan_payload', models.JSONField(blank=True, default=dict)),
                ('memory_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('output_file', models.FileField(blank=True, upload_to='article_outputs/%Y/%m/')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='article_agent.article')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('review_payload', models.JSONField(blank=True, default=dict)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='article_agent.article')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('article', 'position'), name='article_section_position_unique')],
            },
        ),
    ]
