# Generated by Django 6.1.1 on 2026-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_agent', '0002_articlejob_result_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlejob',
            name='checkpoint_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='articlejob',
            name='execution_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='execution_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
